# Generated by Django 3.1.2 on 2020-10-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUserModel', '0005_auto_20201006_1127'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
